### ISSUE TITLE
[DOCUMENTATION] bitmap_opts_t type not documented

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#13]
Documentation of the `bitmap_opts_t` type is missing in the [Types](https://github.com/FrSkyRC/PixelOSD/blob/233e147ba175e0d5cd57e8901535ce0d0372aa6a/doc/OSD.md#types) section

**Comment by fiam** [comment]
Thanks for the heads up. I've just documented it in our internal repo, and I'll update the public docs later today. In the meantime...

### bitmap_opts_t (uint8_t)
Options for bitmap drawing.

Values:
- `BITMAP_OPT_INVERSE` = 1 << 0: Invert black and white colors
- `BITMAP_OPT_SOLID_BACKGROUND` = 1 << 1: Draw a solid gray color where the bitmap has transparent pixels
- `BITMAP_OPT_ERASE_TRANSPARENT` = 1 << 2: Instead of skipping transparent pixels, erase them on the destination
