### ISSUE TITLE
Alt Side Bar Scroll issue 2.0 F722-px

### ISSUE THREAD

**Issue by mtnmikev** [FrSkyRC/PixelOSD#2]
The box that surrounds the numeric variable for altitude cuts off the first digit when above 99 feet.
![Screenshot (360)](https://user-images.githubusercontent.com/20196225/85208710-6af74180-b2e7-11ea-94e8-7aeb1bc10249.png)

**Comment by fiam** [comment]
Thanks for the detailed report! I’ll take care of it for beta2

**Comment by mtnmikev** [comment]
Thank you!  Would it be possible to adjust the width of the side bar spacing?  To have them closer to the outside edges.

**Comment by fiam** [comment]
Everything can be tweaked (width, height, vertical/horizontal offset, number of subdivisions, etc..) by FC, but I would prefer to not expose every possible knob in INAV to avoid having too many settings. Could you post a picture highlighting the width you want to be made adjustable?

**Comment by mtnmikev** [comment]
Also not a big deal but the 100mph graduations might be better as 25 or 50 ? Been trying to figure out how to add the graph feature also.  Is that not user doable yet? 

![InkedScreenshot (360)_LI](https://user-images.githubusercontent.com/20196225/85211430-fd0a4480-b2fd-11ea-922d-86e2f63f1810.jpg)

**Comment by fiam** [comment]
Fixed for beta 2. Before:

<img width="832" alt="Screenshot 2020-06-20 at 21 21 43" src="https://user-images.githubusercontent.com/41529/85211485-b76f6b00-b341-11ea-8035-343a376bc1c0.png">

After:

<img width="832" alt="Screenshot 2020-06-20 at 21 22 21" src="https://user-images.githubusercontent.com/41529/85211487-c1916980-b341-11ea-9f3d-db56ddcfb66e.png">

I'm also updating the INAV fonts for beta2, since it now contains metadata that can let the OSD use the screen space better. Note the difference with this screenshot:

<img width="832" alt="Screenshot 2020-06-20 at 21 23 33" src="https://user-images.githubusercontent.com/41529/85211498-e1c12880-b341-11ea-8af3-fb5d7eb62e7d.png">

The labels are a bit closer to the left of their boxes because the `-` symbol has its width of 8 pixels declared in its metadata, so the label knows it doesn't need a whole 12 pixel slot and can fit all digits using 4 horizontal pixels less.

**Comment by fiam** [comment]
> Also not a big deal but the 100mph graduations might be better as 25 or 50 ? Been trying to figure out how to add the graph feature also. Is that not user doable yet?
> 
> ![InkedScreenshot (360)_LI](https://user-images.githubusercontent.com/20196225/85211430-fd0a4480-b2fd-11ea-922d-86e2f63f1810.jpg)

Thanks for the image. I'll add a setting in INAV to adjust their horizontal distance from the center of the screen? Would that be fine?

Regarding the counts per ladder step, I think you're totally right. 100 counts per step is just too much for some of the scrollable values. I'll add a setting for them and change the defaults depending on what causes it to scroll. Thanks for all the feedback!

**Comment by mtnmikev** [comment]
Wow thanks! Looks and sounds great.

**Comment by fiam** [comment]
@mtnmikev Horizontal offset is done too. I'll add it to beta 2.

<img width="832" alt="Screenshot 2020-06-20 at 22 51 54" src="https://user-images.githubusercontent.com/41529/85212248-e3421f00-b348-11ea-8402-dd36e3b72fa3.png">

**Comment by fiam** [comment]
@mtnmikev I've changed the default counts per sidebar steps to saner values depending on what makes them scroll, but I've also added manual settings so you can set them to any value in the [0, 255] range. You can check the new settings in the INAV PR here https://github.com/iNavFlight/inav/pull/5857/files. I'll put everything together on Tuesday for beta 2.

**Comment by mtnmikev** [comment]
Awesome!   Look forward to loading it up. 

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 20, 2020 at 4:09 PM, Alberto García Hierro<notifications@github.com> wrote:   


@mtnmikev I've changed the default counts per sidebar steps to saner values depending on what makes them scroll, but I've also added manual settings so you can set them to any value in the [0, 255] range. You can check the new settings in the INAV PR here https://github.com/iNavFlight/inav/pull/5857/files. I'll put everything together on Tuesday for beta 2.
