### ISSUE TITLE
Timer assisted sync detection

### ISSUE THREAD

**Issue by expipiplus1** [FrSkyRC/PixelOSD#23]
Does the hardware permit using a timer to assist sync detection in a noisy enrironment?

That is: once several syncs have been found, use them to measure the framerare, and use that to assist in finding syncs in the future.

It's probably easier to add some more filtering on the ESC, but I've already got a large cap on there and get very little detectable visual noise, just the OSD loses sync. 

One problem would be when switching cameras in the air, but I'd gladly sacrifice a few frames of missing/misplaced OSD when switching cameras for more general OSD stability.

**Comment by alberto-frsky** [comment]
Hi @expipiplus1,

Thanks for your suggestion, but there are several reasons why a pure timer based detection wouldn't work, since lots of cameras usually have slight differences in timings and color levels depending on the picture (e.g. some have edge detection algorithms that introduce some time variability). We already do have some means for compensating for some lost lines, but if there's significant noise, at some point the drift becomes too much and the OSD disappears. We opted for not drawing the OSD when we're "unsure" about where the in frame we are, to avoid the possibility of distorting the video sync signal (losing just OSD is better than losing both OSD and video).

**Comment by expipiplus1** [comment]
Sure, that's very sensible.

In that case I'm not sure that the algorithm is conservative enough, as I've certainly experienced the OSD being drawn in the incorrect position.
