### ISSUE TITLE
[DOCUMENTATION] [MINOR] Type of the error code in response should be int8_t

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#8]
Acccording the the [Responses and errors](https://github.com/FrSkyRC/PixelOSD/blob/e1ad2454ea778fd922c0557c6928e6b4aa6e7c97/doc/OSD.md#responses-and-errors) section of the documentation

> Errors are reported using the special 0 command followed by the command identifier that generated the error and an error code, **both as `uint8_t`**

Given the fact that error codes can be negative their type should be int8_t rather then uint8_t as suggested in te quoted part of the documentation.

BTW - do you prefer the documentation related findings (especially the minor ones) to be collected in one issue, or rather have separate issues raised as they are discovered?

**Comment by pawelsky** [comment]
Similarly the pitch and roll values of the `widget_ahi_pitch_roll_t` type are defined as `uint16_t : 12` and the range is given as `[0, 4096]` (BTW the maximum number with 12 bits is 4095). However the next paragraph suggest that the negative values can be used as well (for pitch down/roll counterclockwise).

> Positive pitch values indicate up while positive roll values indicate clockwise rotation.

Shouldn't the the pitch/roll then be of type `int16_t : 12` and the range `[-2048, 2047]`?

**Comment by fiam** [comment]
Thanks for the heads up! The type of the error definitely needs to be changed to `int8_t` in the documentation, otherwise it could be confusing.

Regarding `widget_ahi_pitch_roll_t`, note that the interval is given as `[0, 4096)` which means `4096` is not included in the interval (see https://en.wikipedia.org/wiki/Interval_(mathematics)#Notations_for_intervals for reference). Note that this value is defined as a quantisation of a full rotation, so I think it's easier to grasp as an unsigned value. Negative values can be expressed by either subtracting from `4096` or, depending on the platform/language/compiler/runtime, by using a 12 bit signed value as you suggest. 

For example, in C (which uses two's complement to represent negative values) the binary representation of an unsigned 12 bit value for `4095` would be the same as `-1` for a signed 12 bit (all bits set), and the compiler would take care of all the plumbing if you're using little endian. However, in other languages like Python there's no easy way to express a 12 bit signed integer, that's why I documented it as unsigned.

**Comment by fiam** [comment]
Forgot to mention, please open separate issues for different topics even if they all relate to the documentation. Thanks!

**Comment by pawelsky** [comment]
While I fully understand the idea, maybe at least a bit more explanation could be added to the documentation on why this has been defined like that. Regarding Python both position and rectangle types use int16_t : 12 so you'll have this problem anyway.

Regarding the notation, my bad, wasn't wearing glasses ;-), but since this is set of integers the [0, 4095] would probably be less prone to misreading.
